name: Build API
on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  swaggerhub_owner: MConneely

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Start the API
      run: |
        dotnet run --configuration Release --no-build & sleep 5 # Allow API to start

    - name: Fetch OpenAPI Spec
      run: |
        curl http://localhost:5118/swagger/v1/swagger.json -o openapi.json

    - name: Upload OpenAPI Spec as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenAPI-Spec
        path: openapi.json
  
  validate-api-on-swaggerhub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Validate definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.APIHUB_DESIGN_API_KEY}}      
        run: |
          swaggerhub api:validate:local --organization $swaggerhub_owner --file ./openapi.json --fail-on-critical --json 




