name: Build API
on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore
      
    - name: Install Swashbuckle CLI
      run: dotnet tool install -g Swashbuckle.AspNetCore.Cli
      
    - name: Export OpenAPI Specification
      run: |
        mkdir -p openapi
        dotnet swagger tofile --output openapi/openapi.json bin/Release/net8.0/ToDoApi.dll v1


